services:
  portlocator.api:
    image: ${DOCKER_REGISTRY-}portlocatorapi
    container_name: portlocator-api
    build:
      context: .
      dockerfile: src/portlocator.Api/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    depends_on:
      - portlocator.database
    ports:
      - "5000:5000"

  portlocator.database:
    image: postgres:latest
    container_name: portlocator-database
    environment:
      - POSTGRES_DB=portlocator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
       - 5432:5432
  
  portlocator.test.database:
    image: postgres:latest
    container_name: portlocator-test-database
    environment:
      - POSTGRES_DB=portlocator-test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
       - 5400:5432
